# ---- Build Stage ----
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN rm -f .env
# RUN CGO_ENABLED=0 GOOS=linux go build -o main .
# RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api # Or wherever main.go lives
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api/main.go
# ---- Run Stage ----
FROM alpine:latest
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /app
COPY --from=builder /app/main .
# Ensure the binary is executable
COPY --from=builder /app/docs ./docs
RUN chmod +x main 

USER appuser
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --quiet --tries=1 --spider http://localhost:3000/health || exit 1

CMD ["./main"]